apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-t8kl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-syuw-tenant/rhtap-demo-app/hacbs-test-project-t8kl@sha256:1cd885d142487cc83f31e0705b775ef83163a62cf6475843bb7365de2cf9ec00
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
