apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-t8kl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-t8kl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-t8kl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-t8kl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-t8kl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-syuw-tenant/rhtap-demo-app/hacbs-test-project-t8kl@sha256:1cd885d142487cc83f31e0705b775ef83163a62cf6475843bb7365de2cf9ec00
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
